# Generated by Django 5.2.7 on 2025-11-10 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_alt_text_productimage_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
