# Generated by Django 5.2.7 on 2025-11-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='extra_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
    ]
