# Generated by Django 5.2.7 on 2025-11-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_extra_image_productimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
    ]
