# Generated by Django 5.2.7 on 2025-11-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='price',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7),
        ),
    ]
