# Generated by Django 5.2.7 on 2025-11-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productimage_price_alter_productvariant_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='price',
        ),
    ]
